apiVersion: v1
kind: Service
metadata:
  name: test-python-app-service
  labels:
      app: basic-app
spec:
  selector:
    app: basic-app
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30002